CREATE DATABASE QL_CHUNGCHI
GO
USE QL_CHUNGCHI
GO

CREATE TABLE LOAICC
(
	MALCC CHAR(10) NOT NULL,
	TENLCC NVARCHAR(50) 	
)

ALTER TABLE LOAICC
ADD CONSTRAINT PK_LOAICC PRIMARY KEY(MALCC)

CREATE TABLE CHUNGCHI
(
	MACC CHAR(10) NOT NULL,
	TENCC NVARCHAR(50),
	THOIGIANHOC INT,
	MALCC CHAR(10) NOT NULL
) 
ALTER TABLE CHUNGCHI
ADD CONSTRAINT PK_CHUNGCHI PRIMARY KEY(MACC),
CONSTRAINT FK_CHUNGCHI_LOAICC FOREIGN KEY(MALCC) REFERENCES LOAICC(MALCC)

CREATE TABLE HOCVIEN
(
	MAHV CHAR(10) NOT NULL,
	HOTEN NVARCHAR(30),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	DIACHI NVARCHAR(50)
)
ALTER TABLE HOCVIEN
ADD CONSTRAINT PK_MAHV PRIMARY KEY(MAHV)

CREATE TABLE LOPHOC
(
	MALH CHAR(10) NOT NULL,
	TENLH NVARCHAR(30),
	NGAYBD DATE,
	NGAYKT DATE,
	MACC CHAR(10) NOT NULL,
	HOCPHI INT
)
ALTER TABLE LOPHOC
ADD CONSTRAINT PK_LOPHOC PRIMARY KEY(MALH, MACC),
CONSTRAINT FK_LOPHOC_CHUNGCHI FOREIGN KEY(MACC) REFERENCES CHUNGCHI(MACC)

CREATE TABLE DANGKY
(
	MAHV CHAR(10) NOT NULL,
	MALH CHAR(10) NOT NULL,
	NAGYBD DATE,
	TIENDATCOC INT,
	TIENCONLAI INT
)
ALTER TABLE DANGKY
ADD CONSTRAINT PK_DANGKY PRIMARY KEY(MAHV, MALH),
CONSTRAINT FK_DANGKY_HOCVIEN FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV),
CONSTRAINT FK_DANGKY_LOPHOC FOREIGN KEY(MALH) REFERENCES LOPHOC(MALH)

