CREATE DATABASE QL_THUVIEN
GO
USE QL_THUVIEN
GO

CREATE TABLE TACGIA
(
	MATG CHAR(10) NOT NULL,
	TENTG NVARCHAR(50),
	DIACHI NVARCHAR(50)
)

ALTER TABLE TACGIA
ADD CONSTRAINT PK_TACGIA PRIMARY KEY (MATG)

CREATE TABLE LOAISACH
(
	MALOAI CHAR(10) NOT NULL,
	TENLOAI NVARCHAR(50)
)

ALTER TABLE LOAISACH
ADD CONSTRAINT PK_LOAISACH PRIMARY KEY (MALOAI)

CREATE TABLE NHAXUATBAN
(
	MANXB CHAR(10) NOT NULL,
	TENNXB NVARCHAR(50),
	DCNXB NVARCHAR(50),
	DTNXB CHAR(10)
)

ALTER TABLE NHAXUATBAN
ADD CONSTRAINT PK_NHAXUATBAN PRIMARY KEY(MANXB)

CREATE TABLE SACH
(
	MASH CHAR(10) NOT NULL,
	TENSH NVARCHAR(50),
	MATG CHAR(10) NOT NULL,
	NAMXB DATE,
	MANXB CHAR(10) NOT NULL,
	MALOAI CHAR(10) NOT NULL
)

ALTER TABLE SACH
ADD CONSTRAINT PK_SACH PRIMARY KEY(MASH, MATG,MANXB, MALOAI),
CONSTRAINT FK_SACH_TACGIA FOREIGN KEY(MATG) REFERENCES TACGIA(MATG),
CONSTRAINT FK_SACH_NHAXUATBAN FOREIGN KEY(MANXB) REFERENCES NHAXUATBAN(MANXB),
CONSTRAINT FK_SACH_LOAISACH FOREIGN KEY(MALOAI) REFERENCES LOAISACH(MALOAI)

CREATE TABLE DOCGIA
(
	MADG CHAR(10) NOT NULL,
	TENDG NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	LIENHE CHAR(10),
)
ALTER TABLE DOCGIA
ADD CONSTRAINT PK_DOCGIA PRIMARY KEY(MADG)

CREATE TABLE MUONTRASACH
(
	MADG CHAR(10) NOT NULL,
	MASH CHAR(10) NOT NULL,
	NGAYMUON DATE,
	NGAYTRA DATE,
)

ALTER TABLE MUONTRASACH
ADD CONSTRAINT PK_MUONTRASACH PRIMARY KEY(MADG, MASH),
CONSTRAINT FK_MUONTRASACH_DOCGIA FOREIGN KEY(MADG) REFERENCES DOCGIA(MADG),
CONSTRAINT FK_MUONTRASACH_SACH FOREIGN KEY(MASH) REFERENCES SACH(MASH)

