CREATE DATABASE QL_THUENHA
GO
USE QL_THUENHA
GO

CREATE TABLE LOAINHA
(
	MALN CHAR(10) NOT NULL,
	TENLN NVARCHAR(50),
	GHICHU NVARCHAR(50)
)

ALTER TABLE LOAINHA
ADD CONSTRAINT PK_LOAINHA PRIMARY KEY(MALN)

CREATE TABLE NHA
(
	MANHA CHAR(10) NOT NULL,
	DIACHI NVARCHAR(50),
	TIENTHUE INT,
	MALN CHAR(10)
)

ALTER TABLE NHA
ADD CONSTRAINT PK_NHA PRIMARY KEY(MANHA, MALN),
CONSTRAINT FK_NHA_LOAINHA FOREIGN KEY(MALN) REFERENCES LOAINHA(MALN)

CREATE TABLE KHACHHANG(
	MAKH CHAR(10) NOT NULL,
	TENKH NVARCHAR(50),
	DIACHI NVARCHAR(50),
	DTHOAI CHAR(10),
	KHANANGTHUE INT
)

ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)

CREATE TABLE DANGTIN
(
	MANHA CHAR(10) NOT NULL,
	NGAYDANG DATE NOT NUL,
	THOIHANGDG  INT

)

CREATE TABLE DANGTIN
ADD CONSTRAINT PK_DANGTIN PRIMARY KEY(MANHA, NGAYDANG),
CONSTRAINT FK_DANGTIN_NHA FOREIGN KEY(MANHA) REFERENCES NHA(MANHA)

CREATE TABLE XEMNHA
(
	MANHA CHAR(10) NOT NULL,
	MAKH CHAR(10) NOT NULL,
	NGAYXEMNHA DATE,
	KETLUAN NVARCHAR(20) 
)

ALTER TABLE XEMNHA
ADD CONSTRAINT PK_XEMNHA PRIMARY KEY(MANHA, MAKH)
