CREATE DATABASE QL_CHUNGCHI
GO
USE QL_CHUNGCHI
GO

CREATE TABLE LOAICC
(
	MALCC CHAR(10) NOT NULL,
	TENLCC NVARCHAR(50) 	
)

ALTER TABLE LOAICC
ADD CONSTRAINT PK_LOAICC PRIMARY KEY(MALCC)

CREATE TABLE CHUNGCHI
(
	MACC CHAR(10) NOT NULL,
	TENCC NVARCHAR(50),
	THOIGIANHOC INT,
	MALCC CHAR(10) NOT NULL
) 
ALTER TABLE CHUNGCHI
ADD CONSTRAINT PK_CHUNGCHI PRIMARY KEY(MACC),
CONSTRAINT FK_CHUNGCHI_LOAICC FOREIGN KEY(MALCC) REFERENCES LOAICC(MALCC)

CREATE TABLE HOCVIEN
(
	MAHV CHAR(10) NOT NULL,
	HOTEN NVARCHAR(30),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	DIACHI NVARCHAR(50)
)
ALTER TABLE HOCVIEN
ADD CONSTRAINT PK_MAHV PRIMARY KEY(MAHV)

ALTER
